apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.4.4
          ports:
            - containerPort: 27017
              name: mongo-conn
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    service: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      name: mongo-conn
